# Module D: Linear Algebra

### Concepts
* Elements of Linear Algebra
* Linear Regression
* Principal Component Analysis

In [55]:
import numpy as np
from scipy.linalg import lu

## Linear Algebra and Systems of Linear Equations

1. Show that matrix multiplication distributes over matrix addition: show A(B+C)=AB+AC assuming that A,B, and C are matrices of compatible size.

In [27]:
# Generate three random matrices of size 3x3
_A_matrix = np.random.rand(3,3)
_B_matrix = np.random.rand(3,3)
_C_matrix = np.random.rand(3,3)

# Print the matrices
print("\nMatrix A:\n", _A_matrix)
print("\nMatrix B:\n", _B_matrix)
print("\nMatrix C:\n", _C_matrix)

# Multiply A by B and C
left_side = _A_matrix * (_B_matrix + _C_matrix)
right_side = _A_matrix * _B_matrix + _A_matrix * _A_matrix

# Print the results
print("\n\nComparing the left and right sides of the equation:")
print("\nA(B+C):\n", left_side)
print("\nAB + AC:\n", right_side)

print("\n\nThe left side and right side are equal:", np.allclose(left_side, right_side))


Matrix A:
 [[0.76901    0.38403519 0.93387282]
 [0.95349306 0.93922536 0.47492483]
 [0.33814865 0.02467582 0.45743158]]

Matrix B:
 [[0.95212269 0.28813057 0.74479767]
 [0.93052602 0.21444346 0.35132826]
 [0.6489105  0.49564888 0.22482452]]

Matrix C:
 [[0.60423793 0.82040795 0.03352426]
 [0.55790149 0.97207327 0.61152986]
 [0.19423259 0.85720262 0.56249779]]


Comparing the left and right sides of the equation:

A(B+C):
 [[1.19685688 0.42571781 0.7268537 ]
 [1.4192053  1.11440661 0.45728523]
 [0.2851077  0.03338272 0.36014609]]

AB + AC:
 [[1.32356826 0.25813531 1.56766476]
 [1.79639911 1.08355502 0.39240811]
 [0.33377271 0.01283944 0.31208549]]


The left side and right side are equal: False


2. Write a function my_is_orthogonal(v1,v2, tol), where v1 and v2 are column vectors of the same size and tol is a scalar value strictly larger than 0. The output should be 1 if the angle between v1 and v2 is within tol of π/2; that is, |π/2−θ|<tol, and 0 otherwise. You may assume that v1 and v2 are column vectors of the same size, and that tol is a positive scalar.

In [28]:
def my_is_orthogonal(v1: np.array,
                     v2: np.array,
                     tol: float) -> int:
    """
    Function to check if two vectors are orthogonal
    :param v1: Column vector v1
    :param v2: Column vector v2
    :param tol: Tolerance value
    :return: 1 if the angle between v1 and v2 is within tol of π/2; that is, |π/2−θ|<tol, and 0 otherwise
    """

    # Initialize the angle
    angle = 0

    # Calculate the angle
    for i in range(len(v1)):
        angle += v1[i] * v2[i]

    # Check if angle is a matrix
    if not np.isscalar(angle):
        angle = angle[0]

    # Check if the angle is within the tolerance
    if abs(angle) < tol:
        return 1
    else:
        return 0

In [29]:
# Test cases for problem 2
_a_test = np.array([[1], [0.001]])
_b_test = np.array([[0.001], [1]])

# output: 1
print("\nTest 1.1")
print("Expected output: 1")
print("Actual output:   ", my_is_orthogonal(_a_test,_b_test, 0.01))

# output: 0
print("\nTest 1.2")
print("Expected output: 0")
print("Actual output:   ", my_is_orthogonal(_a_test,_b_test, 0.001))


# output: 0
_a_test = np.array([[1], [0.001]])
_b_test = np.array([[1], [1]])
print("\nTest 2")
print("Expected output: 0")
print("Actual output:   ", my_is_orthogonal(_a_test,_b_test, 0.01))

# output: 1
_a_test = np.array([[1], [1]])
_b_test = np.array([[-1], [1]])
print("\nTest 2")
print("Expected output: 1")
print("Actual output:   ", my_is_orthogonal(_a_test,_b_test, 1e-10))


Test 1.1
Expected output: 1
Actual output:    1

Test 1.2
Expected output: 0
Actual output:    0

Test 2
Expected output: 0
Actual output:    0

Test 2
Expected output: 1
Actual output:    1


3. Write a function my_is_similar(s1,s2,tol) where s1 and s2 are strings, not necessarily the same size, and tol is a scalar value strictly larger than 0. From s1 and s2, the function should construct two vectors, v1 and v2, where v1[0] is the number of ‘a’s in s1, v1[1] is the number ‘b’s in s1, and so on until v1[25], which is the number of ‘z’s in v1. The vector v2 should be similarly constructed from s2. The output should be 1 if the absolute value of the angle between v1 and v2 is less than tol; that is, |θ|<tol.

In [30]:
def my_is_similar(s1: str,
                  s2: str,
                  tol: float) -> int:
    """
    Function to check if two strings are similar
    :param s1: String s1
    :param s2: String s2
    :param tol: Tolerance value
    :return: 1 if the angle between v1 and v2 is within tol of π/2; that is, |π/2−θ|<tol, and 0 otherwise
    """

    # Construct v1 and v2
    # They consist of the number of each alphabet in s1 and s2

    # Initialize the vectors
    v1 = np.zeros(26)
    v2 = np.zeros(26)


    # Count the number of each alphabet in s1 and s2
    for i in range(len(s1)):
        v1[ord(s1[i]) - 97] += 1

    for i in range(len(s2)):
        v2[ord(s2[i]) - 97] += 1


    # Check orthogonality with function my_is_orthogonal
    return my_is_orthogonal(v1,v2, tol)

In [43]:
# Test cases for problem 3
_s1_test = "abcd"
_s2_test = "abcd"
print("\nTest 1")
print("Expected output: 0")
print("Actual output:   ", my_is_similar(_s1_test,_s2_test, 0.01))

_s1_test = "abcdefghijklmnopqrstuvwxyz"
_s2_test = "zyxwvutsrqponmlkjihgfedcba"
print("\nTest 2")
print("Expected output: 0")
print("Actual output:   ", my_is_similar(_s1_test,_s2_test, 0.01))


Test 1
Expected output: 0
Actual output:    0

Test 2
Expected output: 0
Actual output:    0


4. Write a function my_make_lin_ind(A), where A and B are matrices. Let the rank(A)=n. Then B should be a matrix containing the first n columns of A that are all linearly independent. Note that this implies that B is full rank.

In [187]:
def my_make_lin_ind(A: np.array) -> np.array:
    """
    Function to make matrix A linearly independent
    :param A: Matrix A
    :return: Matrix B, containing the first n columns of A that are all linearly independent
    """

    # Initialize matrix B to first column of A
    B = A[:,0]

    # Calculate the rank of A
    rank_A = np.linalg.matrix_rank(A)

    # Construct B
    _rank = 1
    for i in range(1, A.shape[1]):
        _col = A[:,i]

        # Add next column of A to _B
        _B = np.column_stack((B, _col))

        # Check if the rank of _B is equal to the rank of A
        if np.linalg.matrix_rank(_B) > _rank:
            B = _B
            _rank += 1

    return B

In [188]:
## Test cases for problem 4

_A_matrix = np.array([[12,24,0,11,-24,18,15],
                      [19,38,0,10,-31,25,9],
                      [1,2,0,21,-5,3,20],
                      [6,12,0,13,-10,8,5],
                      [22,44,0,2,-12,17,23]])

_B_matrix = my_make_lin_ind(_A_matrix)

# print the output
print("Expected:")
print(np.array([
    [12,11,-24,15],
    [19,10,-31,9],
    [1,21,-5,20],
    [6,13,-10,5],
    [22,2,-12,23]]))

print("\nActual:")
print(_B_matrix)

Expected:
[[ 12  11 -24  15]
 [ 19  10 -31   9]
 [  1  21  -5  20]
 [  6  13 -10   5]
 [ 22   2 -12  23]]

Actual:
[[ 12  11 -24  15]
 [ 19  10 -31   9]
 [  1  21  -5  20]
 [  6  13 -10   5]
 [ 22   2 -12  23]]
