# Module D: Linear Algebra

### Concepts
* Elements of Linear Algebra
* Linear Regression
* Principal Component Analysis

In [1]:
import numpy as np

## Linear Algebra and Systems of Linear Equations

1. Show that matrix multiplication distributes over matrix addition: show A(B+C)=AB+AC assuming that A,B, and C are matrices of compatible size.

In [6]:
# Generate three random matrices of size 3x3
A = np.random.rand(3,3)
B = np.random.rand(3,3)
C = np.random.rand(3,3)

# Print the matrices
print("\nMatrix A:\n", A)
print("\nMatrix B:\n", B)
print("\nMatrix C:\n", C)

# Multiply A by B and C
left_side = A * (B + C)
right_side = A * B + A * C

# Print the results
print("\n\nComparing the left and right sides of the equation:")
print("\nA(B+C):\n", left_side)
print("\nAB + AC:\n", right_side)

print("\n\nThe left side and right side are equal:", np.allclose(left_side, right_side))


Matrix A:
 [[0.77243189 0.22495571 0.95437357]
 [0.26050489 0.25634261 0.85079185]
 [0.34727807 0.77821853 0.06919005]]

Matrix B:
 [[0.56411542 0.06111137 0.61128986]
 [0.96378059 0.04012323 0.08656268]
 [0.23402567 0.24888312 0.55817977]]

Matrix C:
 [[0.61523114 0.13616112 0.84942711]
 [0.41476954 0.07015903 0.55897443]
 [0.83038942 0.39032339 0.78761051]]


Comparing the left and right sides of the equation:

A(B+C):
 [[0.9109649  0.04437757 1.39406967]
 [0.35911904 0.02827004 0.54921771]
 [0.36964802 0.49744235 0.0931153 ]]

AB + AC:
 [[0.9109649  0.04437757 1.39406967]
 [0.35911904 0.02827004 0.54921771]
 [0.36964802 0.49744235 0.0931153 ]]


The left side and right side are equal: True


2. Write a function my_is_orthogonal(v1,v2, tol), where v1 and v2 are column vectors of the same size and tol is a scalar value strictly larger than 0. The output should be 1 if the angle between v1 and v2 is within tol of π/2; that is, |π/2−θ|<tol, and 0 otherwise. You may assume that v1 and v2 are column vectors of the same size, and that tol is a positive scalar.

In [15]:
def my_is_orthogonal(v1,v2, tol):
    """
    Function to check if two vectors are orthogonal
    :param v1: Column vector v1
    :param v2: Column vector v2
    :param tol: Tolerance value
    :return: 1 if the angle between v1 and v2 is within tol of π/2; that is, |π/2−θ|<tol, and 0 otherwise
    """

    # Initialize the angle
    angle = 0

    # Calculate the angle
    for i in range(len(v1)):
        angle += v1[i] * v2[i]

    # Check if angle is a matrix
    if not np.isscalar(angle):
        angle = angle[0]

    # Check if the angle is within the tolerance
    if abs(angle) < tol:
        return 1
    else:
        return 0

In [20]:
# Test cases for problem 2
a = np.array([[1], [0.001]])
b = np.array([[0.001], [1]])

# output: 1
print("\nTest 1.1")
print("Expected output: 1")
print("Actual output:   ", my_is_orthogonal(a,b, 0.01))

# output: 0
print("\nTest 1.2")
print("Expected output: 0")
print("Actual output:   ", my_is_orthogonal(a,b, 0.001))


# output: 0
a = np.array([[1], [0.001]])
b = np.array([[1], [1]])
print("\nTest 2.1")
print("Expected output: 0")
print("Actual output:   ", my_is_orthogonal(a,b, 0.01))

# output: 1
a = np.array([[1], [1]])
b = np.array([[-1], [1]])
print("\nTest 2.2")
print("Expected output: 1")
print("Actual output:   ", my_is_orthogonal(a,b, 1e-10))


Test 1.1
Expected output: 1
Actual output:    1

Test 1.2
Expected output: 0
Actual output:    0

Test 2.1
Expected output: 0
Actual output:    0

Test 2.2
Expected output: 1
Actual output:    1
